### PR TITLE
Move scanner out of the internal

### PR DESCRIPTION
**Pull request by joelmdesouza**

### CODE REVIEW

**Review by avelino — APPROVED** [review]
LGTM

**Comment by joelmdesouza** [comment]
@crgimenes @felipeweb

**Review by felipeweb — CHANGES_REQUESTED** [review]
change imports on mock adapter

**Review by crgimenes — APPROVED** [review]
LGTM

**Comment by joelmdesouza** [comment]
@felipeweb The second commit does this

**Review by felipeweb — APPROVED** [review]

**Pull request merged**
