### PR TITLE
Improve performance on batch inserts

### PR DESCRIPTION
**Pull request by cassiobotaro**
Implement batch insert using multiples values `insert into xxx values (xxx),(xxx)` and also using copy(recommended for large inserts) `copy from`. 

These changes will improve performance, and allows to choice the method used. After all merge's these resources will be documented.

Related to https://github.com/prest/prest/issues/295.

### CODE REVIEW

**Comment by felipeweb** [comment]
lib pq have a data race and i send PR to fix here https://github.com/lib/pq/pull/747

**Comment by felipeweb** [comment]
The data race was our fault. The explanation is here: https://godoc.org/github.com/lib/pq

```
After all data has been processed you should call Exec() once with no arguments to flush all buffered data.
```

**Review by marioidival — APPROVED** [review]
LGTM

**Review by crgimenes — APPROVED** [review]
LGTM

**Pull request merged**
