### PR TITLE
mark functions as test helpers

### PR DESCRIPTION
**Pull request by cassiobotaro**
When using mock, and validate fails, go shows information about mock line number instead of correct line. We should mark functions as helper.

related to https://github.com/prest/prest/issues/310

### CODE REVIEW

**Review by felipeweb — COMMENTED** [review]
to accept this we need to stop support 1.8

**Review by felipeweb — APPROVED** [review]
LGTM

**Review by avelino — CHANGES_REQUESTED** [review]
Requires stop Go 1.8 support, removed travis file and update documentation

**Comment by cassiobotaro** [comment]
@avelino 1.8 support was dropped in https://github.com/prest/prest/commit/f59c1e5

**Comment by felipeweb** [comment]
@cassiobotaro  need to remove from this file too https://github.com/prest/adapters/blob/master/.travis.yml

**Review by crgimenes — APPROVED** [review]
LGTM

**Review by avelino — APPROVED** [review]

**Pull request merged**
